repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.0
    hooks:
      - id: clang-format
        types: [c++]

  - repo: https://github.com/cpplint/cpplint
    rev: 1.5.5
    hooks:
      - id: cpplint
        types: [c++]
        args: ['--filter=-whitespace']

  - repo: https://github.com/python/black
    rev: 21.12b0
    hooks:
    - id: black
      language_version: python3.11
     #isort用于检查import 导入代码
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
